server:
  port: 8081

spring:
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: ${DB_HOST:jdbc:mysql://localhost:3306/diploma}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      hbm2ddl:
        auto: ${DB_DDL_TYPE:validate}
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        show_sql: true
        jdbc:
          batch_size: 10
        temp:
          use_jdbc_metadata_defaults: false

diploma:
  app:
    jwtCookieName: token
    jwtSecret: diplomaSecretKey
    jwtExpirationMs: 86400000 # 24 hours

logging:
  level:
    org.springframework: ERROR
  pattern:
    console: "%d{yy-MM-dd E HH:mm:ss.SSS} %-5p ${PID} --- [%8.15t] %-40.40logger{0} : %m%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
