-- MySQL Script generated by MySQL Workbench
-- Mon May  1 16:31:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `diploma`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`role` ;

CREATE TABLE IF NOT EXISTS `diploma`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`group` ;

CREATE TABLE IF NOT EXISTS `diploma`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`user` ;

CREATE TABLE IF NOT EXISTS `diploma`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `subject` VARCHAR(45) NULL,
  `role_id` INT NOT NULL,
  `group_id` INT NULL,
  PRIMARY KEY (`id`, `role_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_role_idx` (`role_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_group1_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `diploma`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `diploma`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`test` ;

CREATE TABLE IF NOT EXISTS `diploma`.`test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NOT NULL,
  `theme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`exercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`exercise` ;

CREATE TABLE IF NOT EXISTS `diploma`.`exercise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `test_id` INT NOT NULL,
  `question` MEDIUMTEXT NOT NULL,
  `answer` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `test_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_exercise_test1_idx` (`test_id` ASC) VISIBLE,
  CONSTRAINT `fk_exercise_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `diploma`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`group_has_test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`group_has_test` ;

CREATE TABLE IF NOT EXISTS `diploma`.`group_has_test` (
  `group_id` INT NOT NULL,
  `test_id` INT NOT NULL,
  PRIMARY KEY (`group_id`, `test_id`),
  INDEX `fk_group_has_test_test1_idx` (`test_id` ASC) VISIBLE,
  INDEX `fk_group_has_test_group1_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_group_has_test_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `diploma`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_test_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `diploma`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`user_has_exercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`user_has_exercise` ;

CREATE TABLE IF NOT EXISTS `diploma`.`user_has_exercise` (
  `user_id` INT NOT NULL,
  `user_role_id` INT NOT NULL,
  `exercise_id` INT NOT NULL,
  `exercise_test_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_role_id`, `exercise_id`, `exercise_test_id`),
  INDEX `fk_user_has_exercise_exercise1_idx` (`exercise_id` ASC, `exercise_test_id` ASC) VISIBLE,
  INDEX `fk_user_has_exercise_user1_idx` (`user_id` ASC, `user_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_exercise_user1`
    FOREIGN KEY (`user_id` , `user_role_id`)
    REFERENCES `diploma`.`user` (`id` , `role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_exercise_exercise1`
    FOREIGN KEY (`exercise_id` , `exercise_test_id`)
    REFERENCES `diploma`.`exercise` (`id` , `test_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
